blank_issues_enabled: false
contact_links:
  - name: Lucas Carvalho
    url: https://wa.me/5531998163126
    about: Desenvolvedor
  - name: Daniel Francisco
    url: https://wa.me/5531980160125
    about: Desenvolvedor
  - name: Heitor
    url: https://wa.me/5531993760404
    about: Desenvolvedor
  - name: Mateus Cambraia
    url: https://wa.me/5531997876723
    about: Desenvolvedor
